export const SET_VIDEO_SEARCH_LIST = 'SET_VIDEO_SEARCH_LIST';
export const SET_VIDEO_QUEUE = 'SET_VIDEO_QUEUE';
export const ADD_TO_QUEUE = 'ADD_TO_QUEUE';
export const REMOVE_FROM_QUEUE = 'REMOVE_FROM_QUEUE';
export const SET_CURRENT = 'SET_CURRENT';
export const SET_ERROR = 'SET_ERROR';
